image: python:3.11.5


stages:
  - test

unit_tests:
  stage: test
  coverage: /TOTAL.*\s+(\d+\%)$/
  script:
    - pip install poetry
    - poetry install
    - poetry run coverage run -m pytest
    - poetry run coverage report
    - poetry add poetry-dynamic-versioning --dev
deploy:
  stage: test
  script:
    - pip install poetry
    - poetry install
    - poetry build
  only:
    - tags