image: python:3.11.5


stages:
  - test

unit_tests:
  stage: test
  coverage: /TOTAL.*\s+(\d+\%)$/
  script:
    - pip install poetry
    - poetry install
    # - pip install -r requirements.txt
    - poetry run coverage run -m tox
    - poetry run coverage report