image: python:3.11.5


stages:
  - test

unit_tests:
  stage: test
  coverage: /TOTAL.*\s+(\d+\%)$/
  script:
    - poetry install
    - poetry shell
    # - pip install -r requirements.txt
    - coverage run -m tox
    - coverage report