image: python:3.11.5


stages:
  - test

unit_tests:
  stage: test
  coverage: /TOTAL.*\s+(\d+\%)$/
  script:
    - pip install -r requirements.txt
    - poetry install
    - coverage run -m pytest
    - coverage report