image: python:3.11.5


stages:
  - test

unit_tests:
  stage: test
  coverage: /TOTAL.*\s+(\d+\%)$/
  script:
    - pip install poetry
    - poetry install
    - poetry run coverage run -m pytest
    - poetry run coverage report
    - poetry add poetry-dynamic-versioning --dev
  except:
    - tags
deploy:
  script:
    - pip install poetry
    - poetry install
    - poetry build
    - ls dist/
    - echo my-artihmetic-$USER deployement on stable servers
  artifacts:
    paths:
      - dist/*
  only:
    - tags
    - main
deploy:
  script:
    - pip install poetry
    - poetry install
    - poetry build
    - ls dist/
    - echo my-artihmetic-$USER deployement on develop servers
  artifacts:
    paths:
      - dist/*
  except:
    - main
  