name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5' 
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Build and publish
        run: |
          poetry build
          echo "Deploying the project..."
      - name: List dist contents
        run: |
          ls dist/
